version: '3.8'

networks:
  my_network:

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=login_system
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=login_system
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:
